# site settings
title: Chinmaya Mission Seacoast NH
subtitle: To give maximum happiness to maximum people for maximum time
email: seacoastnh.chinmaya@gmail.com
description: Website of Chinmaya Mission Seacoast in NH
baseurl: / # the subpath of your site, e.g. /blog
url: https://chinmayamissionnhseacoast.github.io
root: https://chinmayamissionnhseacoast.github.io
author:
street_address: 1234 Somewhere Road
city: Portsmouth
state: NH
zip_code: 03801
country: United States of America
phone: (999) 999-9999

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Facebook: https://www.facebook.com/chinmayamissiondovernh

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
